name: NPM Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm install
      - run: npm run prod
      - run: git add .
      - run: git config --global user.email "elambro@users.noreply.github.com"
      - run: git config --global user.name "elambro"
      - run: git commit -m 'Built in workflow'
      - run: git push
